# Generated by Django 5.0.3 on 2024-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='adresse_exp',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='poste',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='societe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='adresse_formation',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut_formation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='diplome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='etablissement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
